---
version: '3'

services:

  webapp:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: webapp
    ports:
      - "80:80"
    restart: always
    environment:
      - SECRET_KEY=secret_key
      - UPLOADS_DIR=/var/uploads/
      - FLAG_1=F4J{je_suis_super_fort}
      - FLAG_2=F4J{gg_a_jm_pour_le_dc}
      - FLAG_3=F4J{fake_flag3}
